---
defaults:
  run:
    shell: bash
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: false
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      TEST_DB_SCHEMA: join-server-test
      TEST_DB_USER: root
      TEST_DB_PASSWORD: ''
      TEST_DB_HOST: localhost
      TEST_DB_PORT: 3800
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ibiqlik/action-yamllint@v3.1.0
        with:
          file_or_dir: .
          strict: true
          no_warnings: false
          config_file: .yamllint
      - run: shellcheck --color=never --check-sourced --shell=bash release*.bash
  build:
    needs:
      - lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800
          mysql version: '8.0'
          mysql database: 'join-server-test'
          mysql root password: ''
      - run: mysql -u root < create_database.sql
      - run: echo "./node_modules/.bin" >> $GITHUB_PATH
      - run: npm ci
      - run: npm test
